### ISSUE TITLE
Images "Open With"

### ISSUE THREAD

**Issue by unaxor** [pop-os/cosmic-files#1004]
My image viewer is set to "imv" in Cosmic settings, but when I right-click in Cosmic Files and select "Open With," only Firefox and GIMP are listed. I would expect "imv" to be the default option, as it is set in the Cosmic settings, and also appear in the "Open With" list.

**Comment by jyo64** [comment]
I face the same issue with qimgv

**Comment by KodeBarista** [comment]
This issue is most probably fixed with recent updates, related to mime handling 

<img height="400" alt="Image" src="https://github.com/user-attachments/assets/e464951a-4ad3-4c45-b3df-cf36813fdfad" />

**Comment by Telzhaak** [comment]
_I originally commented this in a duplicate issue, but moved it here, since this is the main issue. Sorry_

Pretty sure this is not solved with cosmic-files 1.8.0

> cosmic-files:
  Installed: 1.8.0\~1788375747\~24.04\~089ad2b
  Candidate: 1.8.0\~1788375747~24.04\~089ad2b
  Version table:
 *** 1.8.0\~1788375747\~24.04\~089ad2b 1001
       1001 http://apt.pop-os.org/release noble/main amd64 Packages
        100 /var/lib/dpkg/status

After editing every `mime.list` I could find and restarting the PC, COSMIC-Files GUI still does not recognize the associated application (VLC). Commands like mimeopen, xdg-open and gio open, however, do recognize VLC.

> NAME="Pop!_OS"
VERSION="24.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 24.04 LTS"
VERSION_ID="24.04"

<img width="2403" height="884" alt="Image" src="https://github.com/user-attachments/assets/c805db20-754b-4200-bbe6-6b7062b3204a" />

If it helps, here is a list of the installed packages containing "xdg", "cosmic" or "mime": https://gist.github.com/Telzhaak/e2a957147ea2db5faaed2955c6cb33fb
