### ISSUE TITLE
COSMIC Files: "Open With" dialog window cuts off title with long filenames and has inconsistent right-side padding

### ISSUE THREAD

**Issue by laurenzpavlosmalisianos** [pop-os/cosmic-files#1296]
System: Fedora Linux 42 with COSMIC DE, default configuration,
Kernel: 6.16.12-200.fc42.x86_64
**COSMIC version:**
```
cosmic-session-1.0.0~beta.1.1-2.fc42.x86_64
cosmic-settings-1.0.0~beta.1.1-1.fc42.x86_64
cosmic-files-1.0.0~beta.1.1-1.fc42.x86_64
```

Resolution: 3840x2160
Scale: 150%

**Description:**
When right-clicking a file in COSMIC Files and selecting "Open With", there are two issues with the dialog title "How do you want to open [filename]?":

1. Long filenames are cut off by the window width without proper text wrapping or ellipsis handling
2. The filename/title in the dialog is missing right-side padding, causing it to run too close to the window edge even on shorter filenames

**Steps to Reproduce:**

1. Have a file with a long filename
2. Right-click the file in COSMIC Files
3. Select "Open With..." from the context menu
4. Observe the dialog title being cut off by the window edge  (Screenshot 1, Screenshot 2)
5. Also notice that even shorter filenames lack proper right-side padding (Screenshot 3)

However, a very short filename is displayed correctly with proper padding (Screenshot 4).

Please note: The issue persists at 100% scale (3840x2160) and at 1920x1080 (100% scale).

**Expected Behavior:**

- The dialog title should have proper right-side padding to prevent text from touching the window edge
- Long filenames should wrap to multiple lines, and once a reasonable line limit is exceeded, the filename should be truncated with ellipsis (...)

Screenshot 1:
<img width="1269" height="1048" alt="Screenshot 1" src="https://github.com/user-attachments/assets/405729c1-465c-49d1-9f1c-f8872c20c228" />

Screenshot 2:
<img width="1314" height="1191" alt="Screenshot 2" src="https://github.com/user-attachments/assets/79faa547-a756-49d9-800f-f043930f3e0a" />

Screenshot 3:
<img width="1263" height="1101" alt="Screenshot 3:" src="https://github.com/user-attachments/assets/f543340a-a5b3-4e01-a026-c3b90acba8f6" />

Screenshot 4:
<img width="1230" height="1081" alt="Screenshot 4" src="https://github.com/user-attachments/assets/55d1433d-771e-4404-9489-5d72a7e96983" />

**Comment by KodeBarista** [comment]
This issue appears to have been fixed.

<img height="300" alt="Image" src="https://github.com/user-attachments/assets/fc4f9aaf-225f-4734-8443-5ca1c8345bbb" />

<img height="300" alt="Image" src="https://github.com/user-attachments/assets/0c63202b-fbb5-4776-8129-22a4a8b7fd55" />

**Comment by laurenzpavlosmalisianos** [comment]
The issue persists with filenames that contain no spaces (see the attached screenshot - the text overflows the dialog edge)

System: Fedora Linux 44 with COSMIC DE, default configuration,
Kernel: 7.0.12-201.fc44.aarch64 
COSMIC version: cosmic-files-1.0.16-1.fc44.aarch64

<img width="1470" height="956" alt="COSMIC Files 'Open With' dialog showing a long filename with no spaces overflowing and being cut off at the right edge of the dialog window, alongside terminal output with system details" src="https://github.com/user-attachments/assets/8f8ed7bb-d870-4091-beee-49f0b23dd0d0" />
