### ISSUE TITLE
Ctrl+L, then Ctrl+A requires Ctrl to be released

### ISSUE THREAD

**Issue by Tolriq** [pop-os/cosmic-files#615]
**Cosmic-files version:** 
```
cosmic-files:
  Installé : 0.1.0~1729134424~22.04~d29baf1
  Candidat : 0.1.0~1729134424~22.04~d29baf1
 Table de version :
 *** 0.1.0~1729134424~22.04~d29baf1 1002
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug description:** 

When pressing CTRL+L to edit the full path we reach a state where ctrl+A to select all does not work and add invisible chars in the url.

**Steps to reproduce:**
Press ctrl+L, then ctrl+A multiple times.
Nothing will select.
Now press shift + home and copy the content.

The pasted content will look like: `/home/tolriq/Documents/release`

**Expected behavior:**

Ctrl+A should select all or at least not add the new chars, currently with the muscle memory it's quite complicated to manage paths.

**Other notes:**

Pressing the pencil near the address bar, does put the full path in a proper state where ctrl+A works.

**Comment by leviport** [comment]
It looks to me like Ctrl+A works after a Ctrl+L if I release the Ctrl key between the two. In other words...
:x: Ctrl+L, then A (with Ctrl still held)
:heavy_check_mark: Ctrl+L, release Ctrl, Ctrl+A

Is this the same for you?

**Comment by Tolriq** [comment]
Ho yes you're right, never tested that, muscle memory is too hard for now, easier to try to adapt to that than shift home.

Since in previous non cosmic files the text was already selected maybe it was the same.

**Comment by iamkartiknayak** [comment]
This seems to have been fixed. Can you verify?

**Comment by Tolriq** [comment]
There's no more bad characters when press CTRL+L then A without releasing CTRL. It still does not select and need to release then press ctrl+A after, but at least there's no corruption so it's now a very minor issue.

**Comment by iamkartiknayak** [comment]
This issue seems to have been fixed.
